export const orderList = [
  {
    order: {
      orderId: '3VK9MY',
      status: 'delivered',
      deliveredAt: '2026-01-30T17:56:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Matthias Hirsch',
        address: 'Havelwelle 1, 14471 Potsdam',
        deliveryNotes: 'Floor: 3 Stock - Fahrstuhl',
      },
      customerNotes: '3 Etage Fahrstuhl',
      items: [
        {
          itemId: 'item_001',
          productId: 'prod_hamburger_schnitzel',
          name: 'Hamburger Schnitzel',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 8.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_002',
          productId: 'prod_weißkrautsalat',
          name: 'Weißkrautsalat',
          quantity: 2,
          category: 'side',
          customizations: [],
          price: 3.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_003',
          productId: 'prod_chicken_nuggets_6',
          name: '6 Hähnchen Nuggets',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Dip',
              priceModifier: 0.0,
            },
          ],
          basePrice: 5.9,
          finalPrice: 5.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_004',
          productId: 'prod_schnitzel_letscho',
          name: 'Schnitzel Letscho',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'mit Ketchup',
              priceModifier: 0.0,
            },
          ],
          basePrice: 9.9,
          finalPrice: 9.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_005',
          productId: 'prod_coca_cola_033_disposable',
          name: 'Coca-Cola 0,33l (MEHRWEG)',
          quantity: 1,
          category: 'beverage',
          size: '0.33l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.5,
          finalPrice: 2.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 30.3,
        deliveryFee: 2.5,
        serviceFee: 0.0,
        deposit: 0.25,
        tax: 2.35,
        total: 35.4,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '7HJ2KL',
      status: 'delivered',
      deliveredAt: '2026-01-30T18:23:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Anna Schmidt',
        address: 'Brandenburger Str. 45, 14467 Potsdam',
        deliveryNotes: 'Klingel defekt, bitte anrufen',
      },
      customerNotes: 'Bitte ohne Zwiebeln',
      items: [
        {
          itemId: 'item_006',
          productId: 'prod_pizza_margherita',
          name: 'Pizza Margherita',
          quantity: 2,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'extra Käse',
              priceModifier: 1.5,
            },
          ],
          basePrice: 7.9,
          finalPrice: 9.4,
          currency: 'EUR',
        },
        {
          itemId: 'item_007',
          productId: 'prod_sprite_05l',
          name: 'Sprite 0,5l',
          quantity: 1,
          category: 'beverage',
          size: '0.5l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 3.2,
          finalPrice: 3.2,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 22.0,
        deliveryFee: 2.0,
        serviceFee: 0.5,
        deposit: 0.25,
        tax: 1.85,
        total: 26.6,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '9PL4MN',
      status: 'in_transit',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Thomas Müller',
        address: 'Am Neuen Garten 12, 14469 Potsdam',
        deliveryNotes: 'Hintereingang benutzen',
      },
      customerNotes: 'Schnell bitte!',
      items: [
        {
          itemId: 'item_008',
          productId: 'prod_currywurst_pommes',
          name: 'Currywurst mit Pommes',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 6.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_009',
          productId: 'prod_fanta_033l',
          name: 'Fanta 0,33l',
          quantity: 2,
          category: 'beverage',
          size: '0.33l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.5,
          finalPrice: 2.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 11.5,
        deliveryFee: 1.5,
        serviceFee: 0.0,
        deposit: 0.5,
        tax: 1.02,
        total: 14.52,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '2QW8RT',
      status: 'preparing',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Sarah Weber',
        address: 'Friedrich-Ebert-Str. 78, 14469 Potsdam',
        deliveryNotes: '2. Etage, Tür rechts',
      },
      customerNotes: 'Vegetarisch bitte',
      items: [
        {
          itemId: 'item_010',
          productId: 'prod_pasta_carbonara',
          name: 'Pasta Carbonara',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'substitution',
              description: 'vegetarische Variante',
              priceModifier: 0.0,
            },
          ],
          basePrice: 9.5,
          finalPrice: 9.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_011',
          productId: 'prod_tiramisu',
          name: 'Tiramisu',
          quantity: 1,
          category: 'dessert',
          customizations: [],
          price: 4.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_012',
          productId: 'prod_water_still_075l',
          name: 'Mineralwasser still 0,75l',
          quantity: 1,
          category: 'beverage',
          size: '0.75l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.8,
          finalPrice: 2.8,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 17.2,
        deliveryFee: 2.5,
        serviceFee: 0.3,
        deposit: 0.25,
        tax: 1.52,
        total: 21.77,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '5TY3UV',
      status: 'delivered',
      deliveredAt: '2026-01-30T16:45:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Michael Koch',
        address: 'Charlottenstr. 34, 14467 Potsdam',
        deliveryNotes: 'An der Rezeption abgeben',
      },
      customerNotes: 'Firma XYZ GmbH',
      items: [
        {
          itemId: 'item_013',
          productId: 'prod_burger_classic',
          name: 'Classic Burger',
          quantity: 3,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'extra Bacon',
              priceModifier: 1.0,
            },
          ],
          basePrice: 8.9,
          finalPrice: 9.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_014',
          productId: 'prod_french_fries_large',
          name: 'Pommes Frites (groß)',
          quantity: 3,
          category: 'side',
          customizations: [],
          price: 3.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_015',
          productId: 'prod_cola_05l',
          name: 'Coca-Cola 0,5l',
          quantity: 3,
          category: 'beverage',
          size: '0.5l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 3.0,
          finalPrice: 3.0,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 49.2,
        deliveryFee: 3.0,
        serviceFee: 1.0,
        deposit: 0.75,
        tax: 3.98,
        total: 57.93,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '8XC6WZ',
      status: 'delivered',
      deliveredAt: '2026-01-30T19:12:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Julia Fischer',
        address: 'Lindenstr. 89, 14467 Potsdam',
        deliveryNotes: 'Erdgeschoss, linke Tür',
      },
      customerNotes: 'Allergiker - keine Nüsse!',
      items: [
        {
          itemId: 'item_016',
          productId: 'prod_salad_caesar',
          name: 'Caesar Salad',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Parmesan',
              priceModifier: 0.0,
            },
          ],
          basePrice: 8.5,
          finalPrice: 8.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_017',
          productId: 'prod_apple_juice_03l',
          name: 'Apfelsaft 0,3l',
          quantity: 1,
          category: 'beverage',
          size: '0.3l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.5,
          finalPrice: 2.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 11.0,
        deliveryFee: 1.5,
        serviceFee: 0.0,
        deposit: 0.25,
        tax: 0.96,
        total: 13.71,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '1AB9YZ',
      status: 'cancelled',
      deliveredAt: null,
      paymentStatus: 'refunded',
      customer: {
        name: 'Peter Wagner',
        address: 'Gutenbergstr. 56, 14467 Potsdam',
        deliveryNotes: '4. Stock, Aufzug vorhanden',
      },
      customerNotes: 'Storniert wegen langer Wartezeit',
      items: [
        {
          itemId: 'item_018',
          productId: 'prod_sushi_box_24',
          name: 'Sushi Box 24 Stück',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 18.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_019',
          productId: 'prod_miso_soup',
          name: 'Miso Suppe',
          quantity: 2,
          category: 'starter',
          customizations: [],
          price: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 25.9,
        deliveryFee: 2.5,
        serviceFee: 0.5,
        deposit: 0.0,
        tax: 2.15,
        total: 31.05,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '4CD2EF',
      status: 'delivered',
      deliveredAt: '2026-01-30T17:34:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Lisa Braun',
        address: 'Schopenhauerstr. 23, 14467 Potsdam',
        deliveryNotes: 'Bitte klingeln',
      },
      customerNotes: 'Extra scharf bitte',
      items: [
        {
          itemId: 'item_020',
          productId: 'prod_thai_curry_chicken',
          name: 'Thai Curry mit Hühnchen',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'modification',
              description: 'extra scharf',
              priceModifier: 0.0,
            },
          ],
          basePrice: 11.9,
          finalPrice: 11.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_021',
          productId: 'prod_jasmine_rice',
          name: 'Jasmin Reis',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 3.0,
          currency: 'EUR',
        },
        {
          itemId: 'item_022',
          productId: 'prod_spring_rolls_4',
          name: 'Frühlingsrollen (4 Stück)',
          quantity: 1,
          category: 'starter',
          customizations: [],
          price: 4.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 19.4,
        deliveryFee: 2.0,
        serviceFee: 0.4,
        deposit: 0.0,
        tax: 1.64,
        total: 23.44,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '7GH5IJ',
      status: 'delivered',
      deliveredAt: '2026-01-30T18:56:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Markus Hoffmann',
        address: 'Kurfürstenstr. 67, 14467 Potsdam',
        deliveryNotes: 'Bei Nachbarn abgeben falls nicht da',
      },
      customerNotes: 'Nachbar: Familie Schmidt, Tür 12B',
      items: [
        {
          itemId: 'item_023',
          productId: 'prod_doner_kebab',
          name: 'Döner Kebab',
          quantity: 2,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Tomate',
              priceModifier: 0.0,
            },
          ],
          basePrice: 6.5,
          finalPrice: 6.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_024',
          productId: 'prod_ayran_025l',
          name: 'Ayran 0,25l',
          quantity: 2,
          category: 'beverage',
          size: '0.25l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 2.0,
          finalPrice: 2.0,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 17.0,
        deliveryFee: 1.5,
        serviceFee: 0.3,
        deposit: 0.0,
        tax: 1.42,
        total: 20.22,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '3KL8MN',
      status: 'preparing',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Nina Becker',
        address: 'Hegelallee 14, 14467 Potsdam',
        deliveryNotes: 'Studentenwohnheim, Zimmer 305',
      },
      customerNotes: 'Besteck nicht vergessen!',
      items: [
        {
          itemId: 'item_025',
          productId: 'prod_ramen_beef',
          name: 'Ramen mit Rindfleisch',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 10.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_026',
          productId: 'prod_edamame',
          name: 'Edamame',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 3.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_027',
          productId: 'prod_green_tea',
          name: 'Grüner Tee',
          quantity: 1,
          category: 'beverage',
          size: '0.3l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 2.5,
          finalPrice: 2.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 16.9,
        deliveryFee: 1.9,
        serviceFee: 0.3,
        deposit: 0.0,
        tax: 1.45,
        total: 20.55,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '6OP1QR',
      status: 'delivered',
      deliveredAt: '2026-01-30T20:15:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'David Schneider',
        address: 'Dortustr. 91, 14467 Potsdam',
        deliveryNotes: 'Gartenhaus, hinter dem Hauptgebäude',
      },
      customerNotes: 'Kontaktlose Lieferung',
      items: [
        {
          itemId: 'item_028',
          productId: 'prod_pizza_salami',
          name: 'Pizza Salami',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 8.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_029',
          productId: 'prod_pizza_hawaii',
          name: 'Pizza Hawaii',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Ananas',
              priceModifier: 0.0,
            },
          ],
          basePrice: 8.9,
          finalPrice: 8.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_030',
          productId: 'prod_beer_05l',
          name: 'Bier 0,5l',
          quantity: 2,
          category: 'beverage',
          size: '0.5l',
          containerType: 'disposable',
          deposit: 0.08,
          customizations: [],
          basePrice: 3.5,
          finalPrice: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 24.8,
        deliveryFee: 2.5,
        serviceFee: 0.5,
        deposit: 0.16,
        tax: 2.15,
        total: 30.11,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '9ST4UV',
      status: 'in_transit',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Emma Klein',
        address: 'Voltaireweg 5, 14469 Potsdam',
        deliveryNotes: 'Seiteneingang benutzen',
      },
      customerNotes: 'Bitte leise klingeln, Baby schläft',
      items: [
        {
          itemId: 'item_031',
          productId: 'prod_pad_thai_shrimp',
          name: 'Pad Thai mit Garnelen',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 12.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_032',
          productId: 'prod_tom_yum_soup',
          name: 'Tom Yum Suppe',
          quantity: 1,
          category: 'starter',
          customizations: [
            {
              type: 'modification',
              description: 'mild',
              priceModifier: 0.0,
            },
          ],
          basePrice: 5.5,
          finalPrice: 5.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 18.4,
        deliveryFee: 2.0,
        serviceFee: 0.4,
        deposit: 0.0,
        tax: 1.58,
        total: 22.38,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '2WX7YZ',
      status: 'delivered',
      deliveredAt: '2026-01-30T19:45:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Frank Schulz',
        address: 'Jägerallee 28, 14469 Potsdam',
        deliveryNotes: 'Beim Pförtner abgeben',
      },
      customerNotes: 'Firma TechStart',
      items: [
        {
          itemId: 'item_033',
          productId: 'prod_burrito_chicken',
          name: 'Chicken Burrito',
          quantity: 4,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'extra Guacamole',
              priceModifier: 1.5,
            },
          ],
          basePrice: 9.5,
          finalPrice: 11.0,
          currency: 'EUR',
        },
        {
          itemId: 'item_034',
          productId: 'prod_nachos_cheese',
          name: 'Nachos mit Käse',
          quantity: 2,
          category: 'side',
          customizations: [],
          price: 5.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_035',
          productId: 'prod_cola_1l',
          name: 'Coca-Cola 1,0l',
          quantity: 2,
          category: 'beverage',
          size: '1.0l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 4.5,
          finalPrice: 4.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 64.0,
        deliveryFee: 3.5,
        serviceFee: 1.5,
        deposit: 0.5,
        tax: 5.28,
        total: 74.78,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '5AB0CD',
      status: 'delivered',
      deliveredAt: '2026-01-30T17:08:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Sabine Meyer',
        address: 'Park Sanssouci 2, 14469 Potsdam',
        deliveryNotes: 'Personaleingang',
      },
      customerNotes: 'Pausenraum',
      items: [
        {
          itemId: 'item_036',
          productId: 'prod_chicken_wings_10',
          name: 'Chicken Wings (10 Stück)',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'BBQ Sauce',
              priceModifier: 0.5,
            },
          ],
          basePrice: 9.9,
          finalPrice: 10.4,
          currency: 'EUR',
        },
        {
          itemId: 'item_037',
          productId: 'prod_onion_rings',
          name: 'Onion Rings',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 3.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_038',
          productId: 'prod_ice_tea_05l',
          name: 'Ice Tea 0,5l',
          quantity: 1,
          category: 'beverage',
          size: '0.5l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.9,
          finalPrice: 2.9,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 17.2,
        deliveryFee: 2.0,
        serviceFee: 0.3,
        deposit: 0.25,
        tax: 1.48,
        total: 21.23,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '8EF3GH',
      status: 'preparing',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Oliver Richter',
        address: 'Nauener Tor 11, 14467 Potsdam',
        deliveryNotes: 'Büro im 2. OG',
      },
      customerNotes: 'Meeting läuft, bitte still sein',
      items: [
        {
          itemId: 'item_039',
          productId: 'prod_sushi_box_16',
          name: 'Sushi Box 16 Stück',
          quantity: 2,
          category: 'main',
          customizations: [],
          price: 14.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_040',
          productId: 'prod_wakame_salad',
          name: 'Wakame Salat',
          quantity: 2,
          category: 'side',
          customizations: [],
          price: 4.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 38.8,
        deliveryFee: 2.5,
        serviceFee: 0.8,
        deposit: 0.0,
        tax: 3.21,
        total: 45.31,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '1IJ6KL',
      status: 'delivered',
      deliveredAt: '2026-01-30T18:32:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Christine Zimmermann',
        address: 'Yorkstr. 44, 14467 Potsdam',
        deliveryNotes: 'Keller, separate Eingangstür',
      },
      customerNotes: 'Yoga-Studio',
      items: [
        {
          itemId: 'item_041',
          productId: 'prod_poke_bowl_salmon',
          name: 'Poke Bowl mit Lachs',
          quantity: 3,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Reis, extra Salat',
              priceModifier: 0.0,
            },
          ],
          basePrice: 11.9,
          finalPrice: 11.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_042',
          productId: 'prod_smoothie_mango',
          name: 'Mango Smoothie',
          quantity: 3,
          category: 'beverage',
          size: '0.4l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 4.9,
          finalPrice: 4.9,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 50.4,
        deliveryFee: 2.5,
        serviceFee: 1.0,
        deposit: 0.0,
        tax: 4.18,
        total: 58.08,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '4MN9OP',
      status: 'delivered',
      deliveredAt: '2026-01-30T16:28:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Stefan Werner',
        address: 'Zeppelinstr. 136, 14471 Potsdam',
        deliveryNotes: 'Laden, Hauptstraße',
      },
      customerNotes: 'Mittagspause 13-14 Uhr',
      items: [
        {
          itemId: 'item_043',
          productId: 'prod_falafel_wrap',
          name: 'Falafel Wrap',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'scharf',
              priceModifier: 0.0,
            },
          ],
          basePrice: 6.5,
          finalPrice: 6.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_044',
          productId: 'prod_hummus_pita',
          name: 'Hummus mit Pita',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 4.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_045',
          productId: 'prod_lemonade_homemade',
          name: 'Hausgemachte Limonade',
          quantity: 1,
          category: 'beverage',
          size: '0.4l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 3.5,
          finalPrice: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 14.9,
        deliveryFee: 1.5,
        serviceFee: 0.0,
        deposit: 0.0,
        tax: 1.31,
        total: 17.71,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '7QR2ST',
      status: 'in_transit',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Petra Hoffmann',
        address: 'Schwertfegerstr. 7, 14467 Potsdam',
        deliveryNotes: 'Dachgeschoss, Treppen',
      },
      customerNotes: 'Klingel kaputt, bitte anrufen',
      items: [
        {
          itemId: 'item_046',
          productId: 'prod_lasagne_bolognese',
          name: 'Lasagne Bolognese',
          quantity: 1,
          category: 'main',
          customizations: [],
          price: 9.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_047',
          productId: 'prod_bruschetta',
          name: 'Bruschetta (4 Stück)',
          quantity: 1,
          category: 'starter',
          customizations: [],
          price: 5.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_048',
          productId: 'prod_wine_red_02l',
          name: 'Rotwein 0,2l',
          quantity: 1,
          category: 'beverage',
          size: '0.2l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 5.9,
          finalPrice: 5.9,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 21.3,
        deliveryFee: 2.0,
        serviceFee: 0.4,
        deposit: 0.0,
        tax: 1.85,
        total: 25.55,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '3UV5WX',
      status: 'delivered',
      deliveredAt: '2026-01-30T19:58:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Andreas Lange',
        address: 'Rudolf-Breitscheid-Str. 52, 14482 Potsdam',
        deliveryNotes: 'Rotes Haus, Gartentür',
      },
      customerNotes: 'Hund bellt, nicht erschrecken',
      items: [
        {
          itemId: 'item_049',
          productId: 'prod_fish_chips',
          name: 'Fish & Chips',
          quantity: 2,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'Remoulade',
              priceModifier: 0.5,
            },
          ],
          basePrice: 10.9,
          finalPrice: 11.4,
          currency: 'EUR',
        },
        {
          itemId: 'item_050',
          productId: 'prod_coleslaw',
          name: 'Coleslaw',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 26.3,
        deliveryFee: 3.0,
        serviceFee: 0.5,
        deposit: 0.0,
        tax: 2.28,
        total: 32.08,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '6YZ8AB',
      status: 'delivered',
      deliveredAt: '2026-01-30T17:22:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Katrin Neumann',
        address: 'Benkertstr. 3, 14467 Potsdam',
        deliveryNotes: 'WG, Name steht nicht am Klingel',
      },
      customerNotes: "Einfach 'Pizza' klingeln",
      items: [
        {
          itemId: 'item_051',
          productId: 'prod_pasta_arrabiata',
          name: 'Pasta Arrabiata',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'modification',
              description: 'extra scharf',
              priceModifier: 0.0,
            },
          ],
          basePrice: 8.5,
          finalPrice: 8.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_052',
          productId: 'prod_garlic_bread',
          name: 'Knoblauchbrot',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 3.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_053',
          productId: 'prod_water_sparkling_075l',
          name: 'Mineralwasser spritzig 0,75l',
          quantity: 1,
          category: 'beverage',
          size: '0.75l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 2.8,
          finalPrice: 2.8,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 15.2,
        deliveryFee: 1.5,
        serviceFee: 0.3,
        deposit: 0.25,
        tax: 1.33,
        total: 18.58,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '9CD1EF',
      status: 'preparing',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Robert Schmitt',
        address: 'Am Kanal 16, 14467 Potsdam',
        deliveryNotes: 'Bootshaus am Wasser',
      },
      customerNotes: 'Direkt am Steg',
      items: [
        {
          itemId: 'item_054',
          productId: 'prod_gyros_pita',
          name: 'Gyros Pita',
          quantity: 2,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'Tzatziki extra',
              priceModifier: 1.0,
            },
          ],
          basePrice: 7.5,
          finalPrice: 8.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_055',
          productId: 'prod_greek_salad',
          name: 'Griechischer Salat',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 6.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_056',
          productId: 'prod_ouzo',
          name: 'Ouzo 2cl',
          quantity: 2,
          category: 'beverage',
          size: '0.02l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 3.0,
          finalPrice: 3.0,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 30.9,
        deliveryFee: 2.5,
        serviceFee: 0.6,
        deposit: 0.0,
        tax: 2.7,
        total: 36.7,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '2GH4IJ',
      status: 'delivered',
      deliveredAt: '2026-01-30T18:07:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Monika Krause',
        address: 'Alleestr. 99, 14469 Potsdam',
        deliveryNotes: 'Praxis Dr. Krause',
      },
      customerNotes: 'Personaleingang hinten',
      items: [
        {
          itemId: 'item_057',
          productId: 'prod_quinoa_bowl',
          name: 'Quinoa Bowl',
          quantity: 3,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'Avocado',
              priceModifier: 2.0,
            },
          ],
          basePrice: 9.9,
          finalPrice: 11.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_058',
          productId: 'prod_carrot_juice_03l',
          name: 'Karottensaft 0,3l',
          quantity: 3,
          category: 'beverage',
          size: '0.3l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [],
          basePrice: 3.5,
          finalPrice: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 46.2,
        deliveryFee: 2.5,
        serviceFee: 0.9,
        deposit: 0.0,
        tax: 3.82,
        total: 53.42,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '5KL7MN',
      status: 'delivered',
      deliveredAt: '2026-01-30T20:41:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Jürgen Wolf',
        address: 'Geschwister-Scholl-Str. 87, 14471 Potsdam',
        deliveryNotes: 'Souterrain Wohnung',
      },
      customerNotes: 'Fußball läuft, schnell bitte!',
      items: [
        {
          itemId: 'item_059',
          productId: 'prod_pizza_quattro_formaggi',
          name: 'Pizza Quattro Formaggi',
          quantity: 2,
          category: 'main',
          customizations: [],
          price: 9.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_060',
          productId: 'prod_pizza_diavola',
          name: 'Pizza Diavola',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'addition',
              description: 'extra Peperoni',
              priceModifier: 1.0,
            },
          ],
          basePrice: 9.5,
          finalPrice: 10.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_061',
          productId: 'prod_beer_pilsner_05l',
          name: 'Pilsner 0,5l',
          quantity: 4,
          category: 'beverage',
          size: '0.5l',
          containerType: 'disposable',
          deposit: 0.08,
          customizations: [],
          basePrice: 3.5,
          finalPrice: 3.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 44.3,
        deliveryFee: 2.5,
        serviceFee: 0.9,
        deposit: 0.32,
        tax: 3.87,
        total: 51.89,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '8OP0QR',
      status: 'in_transit',
      deliveredAt: null,
      paymentStatus: 'paid',
      customer: {
        name: 'Anja Vogel',
        address: 'Hebbelstr. 12, 14467 Potsdam',
        deliveryNotes: 'Altbau, 1. Etage links',
      },
      customerNotes: 'Süße Sachen für Kindergeburtstag',
      items: [
        {
          itemId: 'item_062',
          productId: 'prod_pancakes_nutella',
          name: 'Pancakes mit Nutella',
          quantity: 3,
          category: 'dessert',
          customizations: [
            {
              type: 'addition',
              description: 'Banane',
              priceModifier: 1.0,
            },
          ],
          basePrice: 6.9,
          finalPrice: 7.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_063',
          productId: 'prod_waffles_ice_cream',
          name: 'Waffeln mit Eis',
          quantity: 3,
          category: 'dessert',
          customizations: [],
          price: 7.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_064',
          productId: 'prod_apple_juice_1l',
          name: 'Apfelsaft 1,0l',
          quantity: 2,
          category: 'beverage',
          size: '1.0l',
          containerType: 'disposable',
          deposit: 0.25,
          customizations: [],
          basePrice: 4.2,
          finalPrice: 4.2,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 46.1,
        deliveryFee: 2.0,
        serviceFee: 0.9,
        deposit: 0.5,
        tax: 3.71,
        total: 53.21,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '1ST3UV',
      status: 'delivered',
      deliveredAt: '2026-01-30T16:52:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Claudia Berger',
        address: 'Kaiser-Friedrich-Str. 101, 14469 Potsdam',
        deliveryNotes: 'Beim Friseur',
      },
      customerNotes: 'Bin in Behandlung, einfach abstellen',
      items: [
        {
          itemId: 'item_065',
          productId: 'prod_club_sandwich',
          name: 'Club Sandwich',
          quantity: 1,
          category: 'main',
          customizations: [
            {
              type: 'exclusion',
              description: 'ohne Mayo',
              priceModifier: 0.0,
            },
          ],
          basePrice: 7.9,
          finalPrice: 7.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_066',
          productId: 'prod_sweet_potato_fries',
          name: 'Süßkartoffel Pommes',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 4.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_067',
          productId: 'prod_cappuccino',
          name: 'Cappuccino',
          quantity: 1,
          category: 'beverage',
          size: '0.3l',
          containerType: 'disposable',
          deposit: 0.0,
          customizations: [
            {
              type: 'addition',
              description: 'Hafermilch',
              priceModifier: 0.5,
            },
          ],
          basePrice: 3.5,
          finalPrice: 4.0,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 16.4,
        deliveryFee: 1.5,
        serviceFee: 0.3,
        deposit: 0.0,
        tax: 1.42,
        total: 19.62,
        currency: 'EUR',
      },
    },
  },
  {
    order: {
      orderId: '4WX6YZ',
      status: 'delivered',
      deliveredAt: '2026-01-30T19:29:00Z',
      paymentStatus: 'paid',
      customer: {
        name: 'Martin Stein',
        address: 'Templiner Str. 38, 14473 Potsdam',
        deliveryNotes: 'Einfamilienhaus, blaue Tür',
      },
      customerNotes: 'Familienessen',
      items: [
        {
          itemId: 'item_068',
          productId: 'prod_tagliatelle_salmon',
          name: 'Tagliatelle mit Lachs',
          quantity: 2,
          category: 'main',
          customizations: [],
          price: 12.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_069',
          productId: 'prod_spaghetti_carbonara',
          name: 'Spaghetti Carbonara',
          quantity: 2,
          category: 'main',
          customizations: [],
          price: 9.9,
          currency: 'EUR',
        },
        {
          itemId: 'item_070',
          productId: 'prod_caprese_salad',
          name: 'Caprese Salat',
          quantity: 1,
          category: 'side',
          customizations: [],
          price: 6.5,
          currency: 'EUR',
        },
        {
          itemId: 'item_071',
          productId: 'prod_panna_cotta',
          name: 'Panna Cotta',
          quantity: 2,
          category: 'dessert',
          customizations: [],
          price: 4.5,
          currency: 'EUR',
        },
      ],
      pricing: {
        subtotal: 61.1,
        deliveryFee: 3.0,
        serviceFee: 1.2,
        deposit: 0.0,
        tax: 5.23,
        total: 70.53,
        currency: 'EUR',
      },
    },
  },
];
